### ISSUE TITLE
./bin/tailwindcss needed in PATH

### ISSUE THREAD

**Issue by jeffp42ker** [jacobobryant/platypub-biffweb-theme#1]
Theme script not finding tailwindcss at this point:
```bash
(shell/sh "tailwindcss"
            "-c" "tailwind.config.js"
            "-i" "tailwind.css"
            "-o" "css/main.css"
            "--minify"))
```
Unless I first add the bin dir to PATH:
```
export PATH=$PATH:$PWD/bin
```

**Comment by jacobobryant** [comment]
oh yeah, it assumes that's on the path. I copied it to /usr/local/bin myself, but of course adding the project's bin folder to the path is also fine.

My thinking was that for sandboxing, we'd run themes in a container/Lambda fn that had a fixed set of interpreters/tools pre-installed. And then the theme script can be invoked with a regular `#!/usr/bin/env bb` etc. So it'd be easy to support multiple scripting languages.

That's all tentative though. In any case I'll make a note to mention this in the docs if nothing else. 

On Fri, May 6, 2022, at 9:07 AM, Jeff Parker wrote:
> 
> 
> Theme script not finding tailwindcss at this point:
> 
> (shell/sh "tailwindcss"
>             "-c" "tailwind.config.js"
>             "-i" "tailwind.css"
>             "-o" "css/main.css"
>             "--minify"))
> Unless I first add the bin dir to PATH:
> 
> `export PATH=$PATH:$PWD/bin
`

**Comment by jeffp42ker** [comment]
Thanks, I copied tailwindcss from /home/app/bin/ to /usr/local/bin and the theme works well (so now I'm on to understand what's all is going on in theme script :)  Really great separation of duties, nice job!
